// Execute with `bun src/app/scripts/generate-google-font-info.ts`

import {FontInfo} from '@remotion/google-fonts';
import {execSync} from 'child_process';
import {writeFileSync} from 'fs';
import path from 'path';
import {top250} from './top-250-google-fonts';

type BasicFontInfo = {
	importName: string;
	fontFamily: string;
	previewUrl: string;
};

const googleFonts: FontInfo[] = [];
const basicInfos: BasicFontInfo[] = [];

for (const font of top250) {
	const info = await font.load();
	googleFonts.push(info.getInfo());
	basicInfos.push({
		importName: info.getInfo().importName,
		fontFamily: info.getInfo().fontFamily,
		previewUrl: info.getInfo().url.match(/family=(.*):/)![1],
	});
}

const content = [
	`// Auto-generated by src/app/scripts/generate-google-font-info.ts`,
	'import type {FontInfo} from "@remotion/google-fonts";',
	'import {getRemotionEnvironment} from "remotion";',
	'',
	`if (
  typeof window !== 'undefined' &&
  !getRemotionEnvironment().isStudio &&
  !getRemotionEnvironment().isRendering
) {
  throw new Error(
    'This database should not be imported or executed in the browser, since it is heavy in size.',
  );
}`,
	'',
	`export const GOOGLE_FONTS_DATABASE: FontInfo[] = ${JSON.stringify(
		googleFonts,
		null,
		2,
	)};`,
].join('\n');

writeFileSync(
	path.join(__dirname, '..', 'editor', 'data', 'google-fonts.ts'),
	content,
);

execSync(`npx prettier --write src/editor/data/google-fonts.ts`, {
	stdio: 'inherit',
});

const basicContent = [
	`// Auto-generated by src/app/scripts/generate-google-font-info.ts`,
	`export const GOOGLE_FONTS_LIST = ${JSON.stringify(basicInfos, null, 2)};`,
].join('\n');

writeFileSync(
	path.join(__dirname, '..', 'editor', 'data', 'google-fonts-list.ts'),
	basicContent,
);
execSync(`npx prettier --write src/editor/data/google-fonts-list.ts`, {
	stdio: 'inherit',
});
